CONFIG_XML = 'config.xml'
PROJECT_CONFIG = 'ProjectConfig'
PROJECT_NAME = 'ProjectName'
PROJECT_HOME = 'ProjectHome'
DB_CONFIG = 'DBConfig'
DB_HOST = 'dbhost'
DB_USER = 'dbusername'
DB_PASS = 'dbpassword'
DB_NAME = 'dbname'

PROB_MODEL = 'Probability Distribution Model'
NEGBIN_MODEL = 'Negative Binomial Model'
MNL_MODEL = 'Multinomial Logit Model'
OP_MODEL = 'Ordered Probit Model'
NL_MODEL = 'Nested Logit Model'
SF_MODEL = 'Stochastic Frontier Model'
LOGREG_MODEL = 'Logistic Regression Model'

OP_EQUAL = 'Equal to'
OP_NOTEQUAL = 'Not equal to'
OP_GT = 'Greater than'
OP_GTE = 'Greater than or equal to'
OP_LT = 'Lesser than'
OP_LTE = 'Lesser than or equal to'