CONFIG_XML = 'config.xml'
PROJECT_CONFIG = 'ProjectConfig'
PROJECT_NAME = 'ProjectName'
PROJECT_HOME = 'ProjectHome'
DB_CONFIG = 'DBConfig'
DB_HOST = 'dbhost'
DB_USER = 'dbusername'
DB_PASS = 'dbpassword'