CONFIG_XML = 'config.xml'
PROJECT_CONFIG = 'ProjectConfig'
PROJECT_NAME = 'ProjectName'
PROJECT_HOME = 'ProjectHome'
DB_CONFIG = 'DBConfig'
DB_PROTOCOL = 'protocol'
DB_HOST = 'dbhost'
DB_USER = 'dbusername'
DB_PASS = 'dbpassword'
DB_NAME = 'DBName'
POSTGRES = 'postgres'

MODELCONFIG = 'ModelConfig'
COMP = 'Component'
MODEL = 'Model'
NAME = 'name'
FORMULATION = 'formulation'
MODELTYPE = 'type'
FILTER = 'Filter'
VERTEX = 'vertex'
START = 'start'
END = 'end'
VARIANCE = 'Variance'
VARIABLE = 'Variable'
ALTERNATIVE = 'Alternative'
DEPVARIABLE = 'DependentVariable'
VALUE = 'value'
TABLE = 'table'
COLUMN = 'var'
COND = 'condition'
COEFF = 'coeff'
ID = 'id'
THRESHOLD = 'threshold'
ALTSPEC = 'Alternative Specific'
BRANCH = 'Branch'

PROB_MODEL = 'Probability Distribution'
COUNT_MODEL = 'Count'
MNL_MODEL = 'Multinomial Logit'
GC_MNL_MODEL = 'Multinomial Logit (Generic Choices)'
ORD_MODEL = 'Ordered Choice'
NL_MODEL = 'Nested Logit'
SF_MODEL = 'Stochastic Frontier'
LOGREG_MODEL = 'Logistic Regression'
NEGBIN_MODEL = 'Negative Binomial'
POI_MODEL = 'Poisson'
LOGIT = 'Logit'
PROBIT = 'Probit'

MODELFORM_REG = 'Regression'
MODELFORM_ORD = 'Ordered'
MODELFORM_MNL = 'Multinomial Logit'
MODELFORM_CNT = 'Count'
MODELFORM_NL = 'Nested Logit'

OP_EQUAL = 'Equal to'
OP_NOTEQUAL = 'Not equal to'
OP_GT = 'Greater than'
OP_GTE = 'Greater than or equal to'
OP_LT = 'Lesser than'
OP_LTE = 'Lesser than or equal to'

TABLE_HH = 'households'
TABLE_PER = 'persons'

COMP_LONGTERM = 'Long Term Choices'
COMP_FIXEDACTLOCATION = 'Fixed Activity Location Choices'
COMP_VEHOWN = 'Vehicle Ownership Model'
COMP_FIXEDACTPRISM = 'Fixed Activity Prism Generator'
COMP_CHILDSTATUS = 'Child Daily Status and Allocation Model'
COMP_ADULTSTATUS = 'Adult Daily Status Model'
COMP_ACTSKELRECONCILIATION = 'Activity Skeleton Reconciliation System'
COMP_ACTTRAVSIMULATOR = 'Activity Travel Pattern Simulator'
COMP_ACTTRAVRECONCILIATION = 'Activity Travel Reconciliation System'

COMPKEY_LONGTERM = 'LongTermModels'
COMPKEY_VEHOWN = 'VehicleOwnershipModels'
COMPKEY_FIXEDACTPRISM = 'FixedActivityPrismModels'
COMPKEY_CHILDSTATUS = 'ChildStatusAllocationModels'


COMPMODEL_WORKSTAT = 'Worker Status'
COMPMODEL_NUMJOBS = 'Number of Jobs'
COMPMODEL_PRESCHSTAT = 'School Status: Ages 0 - 4'
COMPMODEL_SCHSTAT1 = 'School Status: Ages 5 - 14'
COMPMODEL_SCHSTAT2 = 'School Status: Ages 15 and over'
COMPMODEL_RESLOC = 'Residential Location Choice'
COMPMODEL_WORKLOC = 'Work Location Choice'
COMPMODEL_PRESCHLOC = 'PreSchool Location: Ages 0 - 4'
COMPMODEL_SCHLOC1 = 'School Location: Ages 5 - 14'
COMPMODEL_SCHLOC2 = 'School Location: Ages 15 and over'
COMPMODEL_NUMVEHS = 'Household Vehicle Counts'
COMPMODEL_NUMTYPES = 'Household Vehicle Types'
COMPMODEL_DAYSTART = 'Daily Prism Start'
COMPMODEL_DAYEND = 'Daily Prism End'
COMPMODEL_NUMWRKEPISODES = 'Number of Work Episodes'
COMPMODEL_WORKSTART1 = 'Work Prism 1 Start'
COMPMODEL_WORKEND1 = 'Work Prism 1 End'
COMPMODEL_WORKSTART2 = 'Work Prism 2 Start'
COMPMODEL_WORKEND2 = 'Work Prism 2 End'
COMPMODEL_NUMSCHEPISODES = 'Number of School Episodes'
COMPMODEL_SCHSTART1 = 'School Prism 1 Start'
COMPMODEL_SCHEND1 = 'School Prism 1 End'
COMPMODEL_SCHSTART2 = 'School Prism 2 Start'
COMPMODEL_SCHEND2 = 'School Prism 2 End'
COMPMODEL_PRESCHSTART = 'PreSchool Prism Start'
COMPMODEL_PRESCHEND = 'PreSchool Prism End'
COMPMODEL_PRESCHDAILYSTAT = 'PreSchool Daily Status'
COMPMODEL_SCHDAILYSTAT = 'School Daily Status: Ages 5 - 17'
COMPMODEL_SCHDAILYINDEP = 'School Daily Independence: Ages 5 - 17'
COMPMODEL_AFTSCHDAILYINDEP = 'After School Daily Independence: Ages 5 - 17'
COMPMODEL_AFTSCHACTSTAT = 'After School Activity Status: Ages 5 - 17'
COMPMODEL_AFTSCHACTTYPE = 'After School Activity Type: Ages 0 - 17'
COMPMODEL_AFTSCHACTDEST = 'After School Activity Destination: Ages 0 - 17'
COMPMODEL_AFTSCHACTDUR = 'After School Activity Duration: Ages 0 - 17'
COMPMODEL_WRKDAILYSTAT = 'Work Daily Status'
COMPMODEL_AFTSCHACTMODE = 'After School Activity Mode for Dependent Children'
COMPMODEL_ACTTYPE = 'Activity Type'
COMPMODEL_ACTDEST = 'Activity Destination'
COMPMODEL_ACTDUR = 'Activity Duration'
COMPMODEL_FIXEDACTMODE = 'Fixed Activity Mode'
COMPMODEL_JOINTACT = 'Joint Activity'
COMPMODEL_TRIPVEH = 'Trip Vehicle'

MODELKEY_WORKSTAT = 'WorkStat'
MODELKEY_NUMJOBS = 'NumJobs'
MODELKEY_PRESCHSTAT = 'PreSchStat'
MODELKEY_SCHSTAT1 = 'SchStat1'
MODELKEY_SCHSTAT2 = 'SchStat2'
MODELKEY_RESLOC = 'ResLoc'
MODELKEY_WORKLOC = 'WorkLoc'
MODELKEY_PRESCHLOC = 'PreSchLoc'
MODELKEY_SCHLOC1 = 'SchLoc1'
MODELKEY_SCHLOC2 = 'SchLoc2'
MODELKEY_NUMVEHS = 'NumVehs'
MODELKEY_NUMTYPES = 'VehTypes'
MODELKEY_DAYSTART = 'DayStart'
MODELKEY_DAYEND = 'DayEnd'
MODELKEY_NUMWRKEPISODES = 'NumWorkEpisodes'
MODELKEY_WORKSTART1 = 'WorkStart1'
MODELKEY_WORKEND1 = 'WorkEnd1'
MODELKEY_WORKSTART2 = 'WorkStart2'
MODELKEY_WORKEND2 = 'WorkEnd2'
MODELKEY_NUMSCHEPISODES = 'NumSchEpisodes'
MODELKEY_SCHSTART1 = 'SchStart1'
MODELKEY_SCHEND1 = 'SchEnd1'
MODELKEY_SCHSTART2 = 'SchStart2'
MODELKEY_SCHEND2 = 'SchEnd2'
MODELKEY_PRESCHDAILYSTAT = 'PreSchDailyStatus'
MODELKEY_SCHDAILYSTAT = 'SchDailyStatus'
MODELKEY_SCHDAILYINDEP = 'SchDailyIndependence'
MODELKEY_AFTSCHDAILYINDEP = 'AfterSchDailyIndependence'
MODELKEY_AFTSCHACTSTAT = 'AfterSchActStatus'
MODELKEY_AFTSCHACTTYPE = 'AftSchActivityType'
MODELKEY_AFTSCHACTDEST = 'AftSchActDestination'
MODELKEY_AFTSCHACTDUR = 'AftSchActDuration'
MODELKEY_WRKDAILYSTAT = 'WorkDailyStatus'
MODELKEY_AFTSCHACTMODE = 'AftSchActivityMode'
MODELKEY_ACTTYPE = 'ActivityType'
MODELKEY_ACTDEST = 'ActDestinationMode'
MODELKEY_ACTDUR = 'ActivityDuration'
MODELKEY_FIXEDACTMODE = 'FixedActivityMode'
MODELKEY_JOINTACT = 'JointActivity'
MODELKEY_TRIPVEH = 'TripVehicle'


COMPMODELMAP = {}
COMPMODELMAP[COMPKEY_FIXEDACTPRISM] = [MODELKEY_DAYSTART,MODELKEY_DAYEND,MODELKEY_NUMWRKEPISODES,
                                       MODELKEY_WORKSTART1,MODELKEY_WORKEND1,MODELKEY_WORKSTART2,MODELKEY_WORKEND2,
                                       MODELKEY_NUMSCHEPISODES,MODELKEY_SCHSTART1,MODELKEY_SCHEND1,MODELKEY_SCHSTART2,
                                       MODELKEY_SCHEND2]

PERSON_TABLE_MODELS = [MODELKEY_DAYSTART,MODELKEY_DAYEND,MODELKEY_NUMWRKEPISODES,
                                       MODELKEY_WORKSTART1,MODELKEY_WORKEND1,MODELKEY_WORKSTART2,MODELKEY_WORKEND2,
                                       MODELKEY_NUMSCHEPISODES,MODELKEY_SCHSTART1,MODELKEY_SCHEND1,MODELKEY_SCHSTART2,
                                       MODELKEY_SCHEND2]

HH_TABLE_MODELS = [MODELKEY_NUMVEHS]





